name: "MTG Proxy"
description: "Bullshit-free MTProto proxy for Telegram (9seconds/mtg v2)"
version: "1.0.0"
slug: "mtg_proxy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
homeassistant: "2023.1.0"
url: "https://github.com/ad/ha-mtg-addon"
ports:
  3128/tcp: 3128
ports_description:
  3128/tcp: "MTProto proxy port"
options:
  secret: ""
  bind_port: 3128
  dns: "8.8.8.8"
schema:
  secret: "str"
  bind_port: "port"
  dns: "str"
